
# Use the official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Install Expo CLI globally
RUN npm install -g expo-cli

ARG MY_IP=000.000.0.000

ENV REACT_NATIVE_PACKAGER_HOSTNAME=$MY_IP
# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the entire project directory to the container
COPY . .
EXPOSE 19000
EXPOSE 19001

CMD ["expo", "start"]